import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js - juniorenv",
    template: "%s | juniorenv",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "#94a3b8", padding: "2rem" }}>
          Header
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer style={{ backgroundColor: "#fb7185", padding: "2rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
